control-center:
    image: confluentinc/cp-enterprise-control-center:5.3.0
    hostname: control-center
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_ZOOKEEPER_CONNECT: "zookeeper:2181"
      CONTROL_CENTER_BOOTSTRAP_SERVERS: "kafka:29092"
      CONTROL_CENTER_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
      - kafka

    networks:
      kafka_copernico_net:
        external:
        name: kafka_copernico_net