---
version: '3.3'

services:

  cassandra:
    container_name: cassandra
    image: datastax/dse-server:6.8.8-ubi7
    environment:
      DS_LICENSE: 'accept'
    ports:
      - 9042:9042
    volumes:
      - ./cassandra/config/cassandra.yaml:/etc/cassandra/cassandra.yaml
    networks:
      kafka_copernico_net:
        ipv4_address: 172.22.0.6

networks:
  kafka_copernico_net:
    external:
      name: kafka_copernico_net
