---
version: '3.3'

services:

  # Begin zookeeper section
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      kafka_copernico_net:
        ipv4_address: 172.22.0.2
  # End zookeeper section


  # Begin kafka brokers section
  kafka1:
    container_name: kafka1
    hostname: kafka1
    image:  confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:29092,PLAINTEXT_HOST://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2

#      KAFKA_METRIC_REPORTERS: "io.confluent.metrics.reporter.ConfluentMetricsReporter"
#      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: "kafka1:29092"
#      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
#      CONFLUENT_METRICS_REPORTER_MAX_REQUEST_SIZE: 10485760
    networks:
      kafka_copernico_net:
        ipv4_address: 172.22.0.5

  kafka2:
    container_name: kafka2
    hostname: kafka2
    image:  confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9093:9093
      - 29093:29093
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:29093,PLAINTEXT_HOST://${DOCKER_HOST_IP:-127.0.0.1}:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2

#      KAFKA_METRIC_REPORTERS: "io.confluent.metrics.reporter.ConfluentMetricsReporter"
#      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: "kafka2:29093"
#      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
#      CONFLUENT_METRICS_REPORTER_MAX_REQUEST_SIZE: 10485760
    networks:
      kafka_copernico_net:
        ipv4_address: 172.22.0.4



  kafka3:
    container_name: kafka3
    hostname: kafka3
    image:  confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9094:9094
      - 29094:29094
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:29094,PLAINTEXT_HOST://${DOCKER_HOST_IP:-127.0.0.1}:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3

#      KAFKA_METRIC_REPORTERS: "io.confluent.metrics.reporter.ConfluentMetricsReporter"
#      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: "kafka3:29094"
#      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
#      CONFLUENT_METRICS_REPORTER_MAX_REQUEST_SIZE: 10485760
    networks:
      kafka_copernico_net:
        ipv4_address: 172.22.0.3



  # End kafka brokers section

  control-center:
    container_name: control-center
    image: confluentinc/cp-enterprise-control-center:latest
    ports:
      - 9021:9021
    environment:
      CONTROL_CENTER_ZOOKEEPER_CONNECT: "zookeeper:2181"
      CONTROL_CENTER_BOOTSTRAP_SERVERS: "kafka1:29092"
      CONTROL_CENTER_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
      - kafka1
      - kafka2
      - kafka3
    networks:
      kafka_copernico_net:
        ipv4_address: 172.22.0.9

networks:
  kafka_copernico_net:
    external:
      name: kafka_copernico_net