# Scrape configuration for default Cinnamon Prometheus HTTP Server on localhost
scrape_configs:
  - job_name: 'cinnamon'
    scrape_interval: 10s
    static_configs:
      - targets: ['seed:9091'] #Seed 9091
      - targets: ['node1:9091'] #Node1 9091
      #- targets: ['localhost:9091'] #Node2 9091
      - targets: ['readside1:9091'] #ReadSide1 9091
      #- targets: ['localhost:9091'] #Readside2 9091
      #- targets: ['localhost:9091'] #Readside3 9091

  - job_name: kamon
    scrape_interval: 10s
    static_configs:
      - targets: ['seed:9095']  #Seed 9095
      #- targets: ['localhost:9096']  #Seed2 9096
      - targets: ['readside1:9095']  #Readside1 9095
      #- targets: ['localhost:9095']  #Readside2 9095


  - job_name: kafka-lag-exporter
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:29092']

  - job_name: clean-up-tool
    scrape_interval: 10s
    static_configs:
      - targets: ['clean-tool:7777']
      - targets: ['clean-tool:9091']
