{
 "title": "PCS Application",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 0 },
   "options": {
    "content": "#                   KAFKA->WRITESIDE\n\n\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 7, "x": 16, "y": 0 },
   "options": {
    "content": "#           WRITESIDE->CASSANDRA\n\n"
   }
  },
  {
   "title": "TOTAL MESSAGES PROCESSED ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(copernico_counters_total{entity=~\"DGR-COP-.*-ProcessedMessagesCounter\"})\n\n"
    }
   ]
  },
  {
   "title": "TOTAL MESSAGES REJECTED ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(copernico_counters_total{app=~\"pcs\", entity=~\".*-RejectedMessagesCounter\"})"
    }
   ]
  },
  {
   "title": "TOTAL EVENTS PERSISTED ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(copernico_counters_total{app=~\"pcs\", entity=~\".*Actor-persisted\"})\n+\nsum(copernico_counters_total{app=~\"pcs\", entity=~\".*Persisted.*-ProcessedMessagesCounter\"})"
    }
   ]
  },
  {
   "title": "TOTAL ERRORS ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(copernico_counters_total{entity=~\"actor-transaction.*_transaction-error\"})"
    }
   ]
  },
  {
   "title": "Kafka Topic Patitions Assgned",
   "type": "gauge",
   "description": "Number of Kafka topic partitions assigned",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "copernico_counters_total{app=~\"pcs\", entity=~\"TopicPartitionsAssigned\"}",
     "legendFormat": "{{entity}}"
    }
   ]
  },
  {
   "title": "Kafka Topic Patitions Revoked",
   "type": "gauge",
   "description": "Number of Kafka topic partitions revoked",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "copernico_counters_total{app=~\"pcs\", entity=~\"TopicPartitionsRevoked\"}",
     "legendFormat": "{{entity}}"
    }
   ]
  },
  {
   "title": "Kafka Processed Messages",
   "type": "graph",
   "description": "Number of Kafka messages processed by WriteSide consumer",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "copernico_counters_total{app=~\"pcs\", entity=~\".*-ProcessedMessagesCounter\"}",
     "legendFormat": "{{entity}}"
    }
   ]
  },
  {
   "title": "Akka Events Persisted",
   "type": "graph",
   "description": "Akka messages persisted in Writeside ",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "copernico_counters_total{app=~\"pcs\", entity=~\".*persisted\"}",
     "legendFormat": "{{entity}}"
    },
    {
     "expr": "copernico_counters_total{app=~\"pcs\", entity=~\".*Persisted.*-ProcessedMessagesCounter\"}",
     "legendFormat": "{{entity}}"
    }
   ]
  },
  {
   "title": "Message consumptions per second (OPS)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "ops", "label": "messages/sec" }
   ],
   "targets": [
    {
     "expr": "\nsum(irate(copernico_counters_total{app=~\"pcs\", entity=~\".*ProcessedMessagesCounter\"}[1m]))",
     "legendFormat": "{{entity}}"
    }
   ]
  },
  {
   "title": "Recoords persisted per second (OPS)",
   "type": "graph",
   "description": "Number of records persisted in Cassandra WriteSide Keyspace",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "ops", "label": "records/sec" }
   ],
   "targets": [
    {
     "expr": "\nsum(irate(copernico_counters_total{app=~\"pcs\", entity=~\".*Actor-persisted\"}[1m]))",
     "legendFormat": "{{entity}}"
    }
   ]
  },
  {
   "title": "Request per minute (RPM)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(copernico_counters_total{app=~\"pcs\", entity=~\".*ProcessedMessagesCounter\"}[1m]))",
     "legendFormat": "{{entity}}"
    }
   ]
  },
  {
   "title": "Request per minute (RPM)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(copernico_counters_total{app=~\"pcs\", entity=~\".*Actor-persisted\"}[1m]))",
     "legendFormat": "{{entity}}"
    }
   ]
  },
  {
   "title": "Actor Transaction Latency Heatmap (ms)",
   "type": "heatmap",
   "description": "Latency of Actor Transaction",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "sum(rate(copernico_histograms_bucket{app=~\"pcs\", entity=~\"actor-transaction-.*_transaction-latency\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}} "
    }
   ]
  },
  {
   "title": "Handler Latency Heatmap (ms)",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "expr": "sum(rate(copernico_histograms_bucket{app=~\"pcs\", entity=~\"actor-transaction-.*_handler-latency\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}} "
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 5, "x": 3, "y": 50 },
   "options": {
    "content": "#                    KAFKA->READSIDE\n\n\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 7, "x": 15, "y": 50 },
   "options": {
    "content": "#           READSIDE->CASSANDRA\n\n"
   }
  },
  {
   "title": "TOTAL PROCESSED MESSAGES",
   "type": "stat",
   "description": "Number of Kafka messages processed by ReadSide Consumer",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(copernico_counters_total{app=~\"readside\", entity=~\".*Persisted.*-ProcessedMessagesCounter\"})"
    }
   ]
  },
  {
   "title": "TOTAL REJECTED MESSAGES",
   "type": "stat",
   "description": "Number of Kafka Messages rejected",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(copernico_counters_total{entity=~\".*SnapshotPersisted-RejectedMessagesCounter\"})\n+\nsum(copernico_counters_total{entity=~\".*PersistedSnapshot-RejectedMessagesCounter\"})"
    }
   ]
  },
  {
   "title": "TOTAL WRITTEN RECORDS",
   "type": "stat",
   "description": "Number of records written in Cassandra Readside keyspace",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(copernico_counters_total{app=~\"readside\", entity=~\".*persisted.*_handler-request\"})"
    }
   ]
  },
  {
   "title": "TOTAL ERRORS ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(copernico_counters_total{app=~\"readside\", entity=~\".*persisted.*_handler-error\"})"
    }
   ]
  },
  {
   "title": "Kafka Processed Messages",
   "type": "graph",
   "description": "Number of Kafka messages processed by ReadSide Consumer",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "copernico_counters_total{app=~\"readside\", entity=~\".*-ProcessedMessagesCounter\"}",
     "legendFormat": "{{entity}}"
    }
   ]
  },
  {
   "title": "Cassandra Records Persisted",
   "type": "graph",
   "description": "Cassandra records persisted in ReadSide ",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "copernico_counters_total{app=~\"readside\", entity=~\".*_persisted.*_handler-request\"}",
     "legendFormat": "{{entity}}"
    }
   ]
  },
  {
   "title": "Transaction Latency Heatmap (ms)",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 67 },
   "targets": [
    {
     "expr": "sum(increase(copernico_histograms_bucket{app=~\"readside\", entity=~\".*persisted.*_handler-latency\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}} "
    }
   ]
  }
 ]
}