---
version: '3.3'

services:

  readside1:
    container_name: readside1
    image: 'readside/readside:1.0'
    ports:
      - '2554:2554'
      - '8554:8559'
      - '8084:8084'
      - '29095:9095'
      - '29091:9091'
      - '5266:5266'
    environment:
      SEED_NODES: 'akka://PersonClassificationServiceReadSide@172.22.4.3:2554'
      KAFKA_BROKERS_LIST: 'kafka:29092'
      STRING_CONEXION_ORACLE: 'jdbc:oracle:thin:@172.22.2.1:1521:xe'
      PASSWORD_ORACLE: '1234'
      USER_ORACLE: 'sys as sysdba'
      CASSANDRA_CONTACT_POINTS: '172.22.0.6:9042'
      PROJECTIONIST_PARALELLISM: 3
      LOGSTASH: '172.22.5.3:5000'
      CLUSTER_IP: 172.22.4.3
      CLUSTER_PORT: 2554
      HTTP_PORT: 8084
      PROMETHEUS_PORT: 9095
      CINNAMON_PORT: 9091
      ZIPKIN_HOST: host.docker.internal
      ZIPKIN_PORT: 9411
      JAEGER_HOST: host.docker.internal
      JAEGER_PORT: 5775
      #PASSIVATE: '20s'
      ENVIRONMENT_EXECUTION: 'DESA'
    networks:
      kafka_copernico_net:
        ipv4_address: 172.22.4.3


  readside2:
    container_name: readside2
    image: 'readside/readside:1.0'
    ports:
      - '2555:2555'
      - '8555:8559'
      - '8085:8085'
      - '5005:9095'
      - '39091:9091'
    environment:
      SEED_NODES: 'akka://PersonClassificationServiceReadSide@172.22.4.3:2555'
      KAFKA_BROKERS_LIST: '172.22.0.5:29092, 172.22.0.0:29093,'
      CASSANDRA_CONTACT_POINTS: '172.22.0.6:9042'

      PROJECTIONIST_PARALELLISM: 3
      LOGSTASH: '172.22.5.3:5000'
      CLUSTER_IP: 172.22.4.4
      CLUSTER_PORT: 2555
      HTTP_PORT: 8085
      PROMETHEUS_PORT: 9095
      CINNAMON_PORT: 9091
      ZIPKIN_HOST: host.docker.internal
      ZIPKIN_PORT: 9411
      JAEGER_HOST: host.docker.internal
      JAEGER_PORT: 5775
      #PASSIVATE: '20s'
    networks:
      kafka_copernico_net:
        ipv4_address: 172.22.4.4

  readside3:
    container_name: readside3
    image: 'readside/readside:1.0'
    ports:
      - '2556:2556'
      - '8556:8559'
      - '8086:8086'
      - '5006:9095'
      - '49091:9091'
    environment:
      SEED_NODES: 'akka://PersonClassificationServiceReadSide@172.22.4.3:2556'
      KAFKA_BROKERS_LIST: '172.22.0.5:29092'
      CASSANDRA_CONTACT_POINTS: '172.22.0.6:9042'

      PROJECTIONIST_PARALELLISM: 3
      LOGSTASH: '172.22.5.3:5000'
      CLUSTER_IP: 172.22.4.5
      CLUSTER_PORT: 2556
      HTTP_PORT: 8086
      PROMETHEUS_PORT: 9095
      CINNAMON_PORT: 9091
      ZIPKIN_HOST: host.docker.internal
      ZIPKIN_PORT: 9411
      JAEGER_HOST: host.docker.internal
      JAEGER_PORT: 5775
      #PASSIVATE: '20s'
    networks:
      kafka_copernico_net:
        ipv4_address: 172.22.4.5

  seed:
    container_name: seed
    image: pcs/pcs:1.0
    ports:
      - '2551:2551'
      - '8558:8558'
      - '8081:8081'
      - '9095:9095'
      - '9091:9091'
    environment:
      SEED_NODES: 'akka://PersonClassificationService@172.22.1.3:2551'
      KAFKA_BROKERS_LIST: 'kafka:29092'
      CASSANDRA_CONTACT_POINTS: '172.22.0.6:9042'
      STRING_CONEXION_ORACLE: 'jdbc:oracle:thin:@172.22.2.1:1521:xe'
      PASSWORD_ORACLE: '1234'
      USER_ORACLE: 'sys as sysdba'
      CONSUMER_PARALLELISM: $CONSUMER_PARALLELISM
      INITIALIZATION: $INITIALIZATION
      NR_PARTITIONS: $NR_PARTITIONS
#      LOGSTASH: '172.22.5.3:5000'
      CLUSTER_IP: 172.22.1.3
      CLUSTER_PORT: 2551
      HTTP_PORT: 8081
      PROMETHEUS_PORT: 9095
      CINNAMON_PORT: 9091
      ZIPKIN_HOST: host.docker.internal
      ZIPKIN_PORT: 9411
      JAEGER_HOST: host.docker.internal
      JAEGER_PORT: 5775
      #PASSIVATE: '20s'
    networks:
      kafka_copernico_net:
        ipv4_address: 172.22.1.3

  seed2:
    container_name: seed2
    image: 'pcs/pcs:1.0'
    ports:
      - '2552:2552'
      - '8082:8082'
      - '9096:9095'
      - '9099:9091'
    environment:
      SEED_NODES: 'akka://PersonClassificationService@172.22.1.4:2552'
      KAFKA_BROKERS_LIST: 'kafka2:29093'
      CASSANDRA_CONTACT_POINTS: '172.22.0.6:9042'
      CONSUMER_PARALLELISM: $CONSUMER_PARALLELISM
      INITIALIZATION: $INITIALIZATION
      NR_PARTITIONS: $NR_PARTITIONS
      #LOGSTASH: '172.22.5.3:5000'
      #CLUSTER_IP: 172.22.1.4 
      CLUSTER_IP: 172.22.1.4
      CLUSTER_PORT: 2552
      HTTP_PORT: 8082
      PROMETHEUS_PORT: 9095
      CINNAMON_PORT: 9091
      ZIPKIN_HOST: host.docker.internal
      ZIPKIN_PORT: 9411
      JAEGER_HOST: host.docker.internal
      JAEGER_PORT: 5775
      #PASSIVATE: '20s'
    networks:
      kafka_copernico_net:
        ipv4_address: 172.22.1.4

  node2:
    container_name: node2
    image: 'pcs/pcs:1.0'
    ports:
      - '2553:2551'
      - '8083:8083'
      - '9097:9095'
      - '9093:9091'
    environment:
      SEED_NODES: 'akka://PersonClassificationService@172.22.1.3:2551'
      KAFKA_BROKERS_LIST: '172.22.0.5:29092'
      CASSANDRA_CONTACT_POINTS: '172.22.0.6:9042'
      CONSUMER_PARALLELISM: $CONSUMER_PARALLELISM
      INITIALIZATION: $INITIALIZATION
      NR_PARTITIONS: $NR_PARTITIONS
      #LOGSTASH: '172.22.5.3:5000'
      CLUSTER_IP: 172.22.1.3
      CLUSTER_PORT: 2553
      HTTP_PORT: 8083
      PROMETHEUS_PORT: 9095
      CINNAMON_PORT: 9091
      ZIPKIN_HOST: host.docker.internal
      ZIPKIN_PORT: 9411
      JAEGER_HOST: host.docker.internal
      JAEGER_PORT: 5775
      #PASSIVATE: '20s'
    networks:
      kafka_copernico_net:
        ipv4_address: 172.22.1.3

  node3:
    container_name: node3
    image: 'pcs/pcs:1.0'
    ports:
      - '2554:2551'
      - '8084:8084'
      - '5004:9095'
      - '39091:9091'
    environment:
      SEED_NODES: 'akka://PersonClassificationService@172.22.1.3:2551'
      KAFKA_BROKERS_LIST: '172.22.2.5:29092, 172.22.2.6:39092'
      CASSANDRA_CONTACT_POINTS: '172.22.0.6:9042'
      CONSUMER_PARALLELISM: $CONSUMER_PARALLELISM
      INITIALIZATION: $INITIALIZATION
      #LOGSTASH: '172.22.5.3:5000'
      CLUSTER_IP: 172.22.1.4
      CLUSTER_PORT: 2553
      HTTP_PORT: 8084
      PROMETHEUS_PORT: 9095
      CINNAMON_PORT: 9091
      ZIPKIN_HOST: host.docker.internal
      ZIPKIN_PORT: 9411
      JAEGER_HOST: host.docker.internal
      JAEGER_PORT: 5775
      #PASSIVATE: '20s'
    networks:
      kafka_copernico_net:
        ipv4_address: 172.22.1.4

  node4:
    container_name: node4
    image: 'pcs/pcs:1.0'
    ports:
      - '2555:2551'
      - '8085:8085'
      - '5005:9095'
      - '9095:9091'
    environment:
      SEED_NODES: 'akka://PersonClassificationService@172.22.1.3:2551'
      KAFKA_BROKERS_LIST: '172.22.2.5:29092, 172.22.2.6:39092'
      CASSANDRA_CONTACT_POINTS: '172.22.0.6:9042'
      CONSUMER_PARALLELISM: $CONSUMER_PARALLELISM
      INITIALIZATION: $INITIALIZATION
      #LOGSTASH: '172.22.5.3:5000'
      CLUSTER_IP: 172.22.1.5
      CLUSTER_PORT: 2553
      HTTP_PORT: 8085
      PROMETHEUS_PORT: 9095
      CINNAMON_PORT: 9091
      ZIPKIN_HOST: host.docker.internal
      ZIPKIN_PORT: 9411
      JAEGER_HOST: host.docker.internal
      JAEGER_PORT: 5775
      #PASSIVATE: '20s'
    networks:
      kafka_copernico_net:
        ipv4_address: 172.22.1.5

networks:
  kafka_copernico_net:
    external:
      name: kafka_copernico_net
